function output = PrecomputationCarrMadanParameters(N,alpha,gridSpace,simpsonIntegrand)

lambda=2*pi/N/gridSpace;
b=lambda*N/2;
k=[-b:lambda:b-lambda];
v = [0:gridSpace:(N-1)*gridSpace];
u = v-(alpha+1)*1i;

% Following (sub)parameters are used in the calculation of the carr madan formula.
% They are independent of the actual (heston) model parameters. Hence, they can be precomputed one time for performance purposes.
rhoDenominator = alpha^2+alpha-v.^2+1i*(2*alpha+1)*v;
fftMultiplier = exp(1i*v*b).*gridSpace;
realStrikes = exp(k);
if(simpsonIntegrand==1)
	simpson_1 = (1/3); 
	simpson = ((3 + (-1).^(2:1:N))/3); simpson = [simpson_1 simpson];
	fftMultiplier = fftMultiplier.*simpson;
end;

CarrMadanPrecomputed = struct('N',N, ...
					'alpha',alpha, ...
					'gridSpace',gridSpace, ...
					'lambda',lambda, ...
					'b',b, ...
					'k',k, ...
					'v',v, ...
					'u',u, ...
					'rhoDenominator',rhoDenominator, ...
					'fftMultiplier',fftMultiplier, ...
					'realStrikes',realStrikes ...
					);
					
output=CarrMadanPrecomputed;